### ISSUE TITLE
Notify the dry-run if people do not put the `--force` option

### ISSUE THREAD

**Issue by Natim** [artines1/Fonts-ResistFingerprinting#1]
Add a warning that the command run in dry-mode in case the --force options is missing.

**Comment by artines1** [comment]
Does the line #198-199 of upload_fonts.py serves this purpose?

**Comment by Natim** [comment]
> Does the line #198-199 of upload_fonts.py serves this purpose?

Yes indeed 👍 

Fixed in https://github.com/artines1/Fonts-ResistFingerprinting/commit/ee32a0b4dd9a799391e628f4e39d794923c9a267
